# Generated by Django 6.0.6 on 2026-06-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('compatibilidad', models.CharField(choices=[('S', 'Ruta (S)'), ('T', 'Todo Terreno (T)'), ('U', 'Universal (U)')], default='U', max_length=1)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
